### ISSUE TITLE
Short/invalid generated token on ios.

### ISSUE THREAD

**Issue by clbolina** [CrossGeeks/PushNotificationPlugin#10]
Hi,
The token generated on ios is to short and invalid to send messages from firebase panel or from rest api.
Android version is ok.

Any sujestion?

Congratulations for your job.

Carlos Bolina.

**Comment by rdelrosario** [comment]
Seems you are using FCM on iOS. Please use https://github.com/CrossGeeks/FirebasePushNotificationPlugin instead. Since you are using FCM on both platforms ios and android.

This one you are using is to work specifically with ios APS and android FCM. It has not FCM support on ios platform unless you provide it. so use the Firebase Push Notification plugin instead which already has FCM support for iOS and Android.
