### ISSUE TITLE
Q: Unable to show notification tray

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [CrossGeeks/PushNotificationPlugin#24]
Hi,
Very useful plugin.

I downloaded sample and got token then tried sending notification using [https://pushtry.com/](url) . It hit the OnNotificationReceived but could not show tray. Is there some setting I need to add to show the tray on top of screen.

**Comment by rdelrosario** [comment]
You mean a heads up notification?

**Comment by avinashramireddy-rapidd** [comment]
Yes. I was in debug mode and I got token and when I pasted in pushtry,nothing happened. 

Update:When I try to send from FCM notification, it sent successfully and at this time I was in release mode. I received notification in my mobile but there was delay in receiving. 

Q:How to test "when notification in background(means app is closed) in debug mode"  .When I close the app it gets disconnected.

**Comment by rdelrosario** [comment]
You mean you are not getting notifications when app closed?

**Comment by avinashramireddy-rapidd** [comment]
Now I am getting. Didn't do anything extra. Its working now as explained above.

But now I would like to know how to test "when app is closed scenario" in debug mode.

**Comment by rdelrosario** [comment]
To test on debug the closed scenario you should:

1. Run the application in debug
2. Stop debugging
3. Reopen application
4. Close application again

After that, you should get notifications just fine when application is closed on a debug build.

Unfortunately, you cannot debug this scenario because application is closed. But you could see what's going on using Device Monitor and a filter for your app if need to see any logs of what's going on.

**Comment by rdelrosario** [comment]
Will close this issue for now if you ate still having problema please feel free to reopen or create a new issue.
