### ISSUE TITLE
PushNotificationManager not found in Droid solution

### ISSUE THREAD

**Issue by NeedNap** [CrossGeeks/PushNotificationPlugin#37]
I updated the plugin version from 1.1.5 to the last versions (1.2.2) but I can't build in Android because the PushNotificationManager is not found.

I had to downgrade to 1.1.5 to make it work again.

**Comment by fabiovank** [comment]
Same here!

**Comment by rdelrosario** [comment]
Have you tried the sample? PushNotificationManager is there. It has installed latest version

**Comment by NeedNap** [comment]
I installed the library from nuget so I don't have the sample files.
I tried to remove the plugin from the PCL and Droid solutions, then I added it again but the result does not change.
It seems that the PushNotificationManager class is not in the Plugin.PushNotification namespace.
I don't know what the problem is, but in the past I updated the library without issues.
At the moment I am using the previous version. If you have any suggestion let me know so I can do try it.
Thanks

**Comment by simon25608** [comment]
#26

**Comment by fusionconsulting** [comment]
Same issue here. Installed from NuGet but PushNotificationManager does not exist in Droid project.

**Comment by rdelrosario** [comment]
Please try latest version and let me know if still an issue.

Also try uninstalling your current version and then installing the new one. Confirm your dependencies is as the NuGet packages needs.

**Comment by NeedNap** [comment]
I updated the library to the latest version and now it works!
Thank you

**Comment by kikolopes90** [comment]
Same issue here. I uninstalled and installed PushNotification but PushNotificationManager does not exist any Droid project.

**Comment by kikolopes90** [comment]
It's because of the new project, I've already tested the old project and it works.

**Comment by kikolopes90** [comment]
I have already encountered problem, because of Target Android Framework, if using "Android 8.0 Oreo" appears "PushNotificationManager" if using "Android 7.1 Nougat" or lower will not appear "PushNotificationManager"

How it works:
1. Uninstall nuget "PushNotificationPlugin"
2. Android Properties > Target Framework: "Use Latest Platform (Android 8.0 Oreo)"
3. Close Visual Studio and open again
4. Install nuget "PushNotificationPlugin" and ready, will appear "PushNotificationManager"

**Comment by kikolopes90** [comment]
I have already encountered problem, because of Android Version (Target Framework).
If you use "Android 8.0 Oreo", install nuget "PushNotificationPlugin 1.2.4" and appears "PushNotificationManager".
If you use "Android 7.1 Nougat" or lower, install nuget "PushNotificationPlugin 1.2.4" and not appears "PushNotificationManager".

How it works:
1º Uninstall nuget "PushNotificationPlugin"
2º Android Properties > Target Framework: "Use Latest Platform (Android 8.0 Oreo) or Android 8.0 Oreo"
3º Close Visual Studio and open again
4º Install nuget "PushNotificationPlugin 1.2.4" and ready, will appear "PushNotificationManager"

**Edit:** Xamarin Forms not yet ready for "Android 8.0 Oreo". Soon will update "Xamarin Forms".
