### ISSUE TITLE
Android: OnNotificationReceived raised instead of OnNotificationOpened for Default action

### ISSUE THREAD

**Issue by NGumby** [CrossGeeks/PushNotificationPlugin#63]
I have the following init code in application OnCreate: 
```
            PushNotificationManager.Initialize(this, new CSPushNotificationHandler(), false);

            var notificationCategories = new NotificationUserCategory[]
                {
                    new NotificationUserCategory("navigate",new List<NotificationUserAction> {
                        new NotificationUserAction("Dismiss","Dismiss", NotificationActionType.Default),
                        new NotificationUserAction("Navigate","Navigate To", NotificationActionType.Foreground)
                    })
                };
            PushNotificationManager.RegisterUserNotificationCategories(notificationCategories);

            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                Console.WriteLine("Notification received !!!");
            };
            CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                Console.WriteLine("Notification opened !!!");
            };
```
On my Android 7.0 device, if I click on the notif directly, or on the Navigate button, I receive the OnNotificationOpened.  But the Dismiss button just gives me a second OnNotificationReceived.  Same results if the app is in foreground or background.

Using latest stable version of the plugin and xamarin.

**Comment by Emixam23** [comment]
Hey I have the same issue !

When I click on the notification, OnNotificationReceived is raised instead of OnNotificationOpened, why?

Best,

Max

**Comment by rdelrosario** [comment]
When using notification categories if you set the user action **NotificationActionType.Default** _(Considered as a background event)_ it will fire the OnNotificationReceived event with an additional key on the payload called **action_identifier** which indicates the option was tapped.

If you set **NotificationActionType.Foreground** on the user action you will get OnNotificationOpened event fired.

I'm planning on adding a new event called **OnNotificationAction** for the background event  **NotificationActionType.Default**  use case, so that is less confusing.

**Comment by Emixam23** [comment]
Hi,

I am not sure to understand what you said about the categories.. Are you saying that based on a certain notification, you can then attribute a certain category?

If so, then how to you link the category and the notification?

Sorry but I am not sure to understand..

Best,

Max
